apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: oracle-update-cronjob
spec:
  project: default
  source:
    repoURL: https://github.com/your-username/oracle-update-all.git
    path: oracle-update-cronjob/manifests
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
