apiVersion: batch/v1
kind: CronJob
metadata:
  name: oracle-update-job
spec:
  schedule: "*/20 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: oracle-update
            image: python:3.10-slim
            command: ["python", "/scripts/update_column.py"]
            env:
            - name: ORACLE_USER
              valueFrom:
                secretKeyRef:
                  name: oracle-secret
                  key: username
            - name: ORACLE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: oracle-secret
                  key: password
            - name: ORACLE_DSN
              valueFrom:
                secretKeyRef:
                  name: oracle-secret
                  key: dsn
            volumeMounts:
            - name: script-volume
              mountPath: /scripts
          restartPolicy: OnFailure
          volumes:
          - name: script-volume
            configMap:
              name: oracle-update-scripts
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: oracle-update-scripts
data:
  update_column.py: |
    import os
    import oracledb

    user = os.getenv("ORACLE_USER")
    password = os.getenv("ORACLE_PASSWORD")
    dsn = os.getenv("ORACLE_DSN")

    connection = oracledb.connect(user=user, password=password, dsn=dsn)
    cursor = connection.cursor()
    cursor.execute("UPDATE my_table SET my_column = 'updated' WHERE ROWNUM <= 1")
    connection.commit()
    cursor.close()
    connection.close()
